#!/bin/sh

# Read variables passed on by GIT
read OLDREV NEWREV REFNAME

# Find out basic variables
GIT_EXEC=`which git`
REPO=`basename $PWD`

# User is commiter of either last or first commit
NULLREV="0000000000000000000000000000000000000000"
[ "$NEWREV" == "$NULLREV" ] && USER_REV="$OLDREV" || USER_REV="$NEWREV"
USER=`$GIT_EXEC log -1 $USER_REV --format="%an"`
BRANCH=${REFNAME#refs/heads/}

# Setup gitweb links
if [ -n "$GITWEB" ]
then
  USER_LINK="<a href=\"http://$GITWEB/?p=$REPO;a=search;s=$USER;st=author\">$USER</a>"
  BRANCH_LINK="<a href=\"http://$GITWEB/?p=$REPO;a=shortlog;h=$REFNAME\">$BRANCH</a>"
  REPO_LINK="<a href=\"http://$GITWEB/?p=$REPO;a=summary\">$REPO</a>"
else
  USER_LINK=$USER
  BRANCH_LINK=$BRANCH
  REPO_LINK=$REPO
fi

# Construct message
if [ "$OLDREV" == "$NULLREV" ]
then
  MSG="$USER_LINK created branch $BRANCH_LINK of $REPO_LINK"
elif [ "$NEWREV" == "$NULLREV" ]
then
  MSG="$USER_LINK deleted branch $BRANCH of $REPO_LINK"
else
  TITLE="$USER_LINK pushed to branch $BRANCH_LINK of $REPO_LINK"
  if [ -n "$GITWEB" ]
  then
    LOG=`$GIT_EXEC log $OLDREV..$NEWREV --format="- %s (<a href=\"http://$GITWEB/?p=$REPO;a=commit;h=%H\">%h</a>)"`
  else
    LOG=`$GIT_EXEC log $OLDREV..$NEWREV --format="- %s (%h)"`
  fi
  if [ -n "$REDMINE" ]
  then
    LOG=`echo $LOG | sed "s/#\([0-9]*\)/#<a href=\"http:\/\/$REDMINE\/issues\/\1\">\1<\/a>/g"`
  fi
  MSG="$TITLE\n$LOG"
fi

# Send it to HipChat
echo -e "$MSG" | $HIPCHAT_SCRIPT -t "$HIPCHAT_TOKEN" -r "$HIPCHAT_ROOM" -f "$HIPCHAT_FROM"
